#7: REST API Client
ripe-tech/ripe-registry-api-js pull request #2
Opened 2020-08-03 15:48 UTC by BeeMargarida

| - | - |
| --- | --- |
| Issue | Closes https://github.com/ripe-tech/ripe-registry/issues/7|
| Dependencies | -- |
| Decisions | APIs for the routes in [ripe-registry](https://github.com/ripe-tech/ripe-registry) and respective type declarations and documentation. Unit tests for the PersonAPI, which is the only one not using mocked data. |
| Animated GIF | <img width="2560" alt="Screenshot 2020-08-03 at 16 44 57" src="https://user-images.githubusercontent.com/25725586/89201214-0d723800-d5a9-11ea-803f-75dae27d19c5.png"><img width="2560" alt="Screenshot 2020-08-03 at 16 45 05" src="https://user-images.githubusercontent.com/25725586/89201195-0519fd00-d5a9-11ea-8c5e-2241169f0674.png"><img width="866" alt="Screenshot 2020-08-03 at 16 47 01" src="https://user-images.githubusercontent.com/25725586/89201178-01867600-d5a9-11ea-9b3c-8fdf362ec1ef.png">|

2020-08-04 08:15 UTC, NFSS10 requested changes

2020-08-04 08:15 UTC, NFSS10 commented on js/client.js
> +         * - 'name' - The name of the client.
I'm not sure `name` is allowed in `body`

2020-08-04 08:15 UTC, NFSS10 commented on js/client.js
> +        async getClients() {
Shouldn't it be `listClients()` ?

Same question for the other of endpoints that list stuff

2020-08-04 08:15 UTC, NFSS10 commented on js/person.js
> +         * - 'email' - The e-mail of the person.
I'm not sure if `email` is allowed in `body`

2020-08-04 08:15 UTC, NFSS10 commented on js/client.js
> +        async getClientProjects(name) {
Shouldn't it be `listClientProjects(name)` ?

2020-08-04 08:15 UTC, NFSS10 commented on js/person.js
> +        async getPersonProjects(email) {
Shouldn't it be `listPersonProjects(email)` ?

2020-08-04 08:15 UTC, NFSS10 commented on js/person.js
> +        async getPersonClients(email) {
Shouldn't it be `listPersonClients(email)` ?

2020-08-04 08:15 UTC, NFSS10 commented on js/project.js
> +         * - 'name' - The unique project's name, used to identify and differentiate from the other projects.
I'm not sure if `name` is allowed in `body`

2020-08-04 08:15 UTC, NFSS10 commented on js/project.js
> +        async getProjectIterations(name) {
Shouldn't it be `listProjectIterations(name)`

2020-08-04 08:15 UTC, NFSS10 commented on test/api/base.js
> +    it("should be able to list the existing person", async () => {
Maybe change "list" to "get"

2020-08-04 08:15 UTC, NFSS10 commented on test/api/base.js
> +        const api = new ripe.API();
As the API is always the same, maybe move `const api = new ripe.API();` to line 5.
After`describe("PersonAPI", function() {` and before `it("should be able to construct a new person", async () => {`

2020-08-04 08:15 UTC, NFSS10 commented on types/client.d.ts
> +    getClients(): Array<Client>;
If you change `getClients` to `listClients`, don't forget to update the remaining interfaces

2020-08-04 08:15 UTC, NFSS10 commented on types/client.d.ts
> +    getClient(name: number): Client;
`getClient(name: number): Client;` should be `getClient(name: string): Client;` right?

2020-08-04 08:15 UTC, NFSS10 commented on types/person.d.ts
> +    deletePerson(email:string): Person;
Missing space `email:string` -> `email: string`

2020-08-04 08:25 UTC, NFSS10 approved these changes

2020-08-05 09:41 UTC, BeeMargarida commented on js/client.js
> +            console.log(url);
oops

2020-08-05 11:02 UTC, gcandal approved these changes

2020-08-05 11:04 UTC, gcandal approved these changes

2020-08-05 17:03 UTC, joamag requested changes

2020-08-05 17:03 UTC, joamag commented on types/project.d.ts
> +    createProject(body: object): Project;
use `Project` type  for the input (make id optional)

2020-08-05 17:03 UTC, joamag commented on types/person.d.ts
> +    createPerson(body: object): Person;
Use use `Person` type for the input (make id optional)

2020-08-05 17:03 UTC, joamag commented on js/client.js
> +         * - 'website' - The client's website URL.
No need to comment on the fields of the payload using the type description instead.
Rename this to `payload` instead of boyd

2020-08-06 09:34 UTC, gcandal approved these changes

2020-08-06 13:47 UTC, joamag requested changes

2020-08-06 13:47 UTC, joamag commented on types/client.d.ts
> +export interface Client {
Create the `ClientPatch` interface that has all of the fields as optional.
Client the `ClientCreate` with the definition of mandatory and non-mandatory fields.

2020-08-06 15:31 UTC, gcandal approved these changes

2020-08-08 10:09 UTC, joamag approved these changes

2020-08-08 10:09 UTC, joamag approved these changes

2020-08-08 10:09 UTC, merged

2020-08-08 10:12 UTC, joamag commented
@gcandal let's try to have CI/CD on the esdocs generation using vercel