Support for options argument in list methods
ripe-tech/ripe-registry-api-js pull request #7
Opened 2020-09-08 14:44 UTC by NFSS10

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-registry-ui/pull/12#discussion_r484762894 |
| Dependencies | -- |
| Decisions | List methods of the ripe-registry API client can now receive options argument wich can be used to, for example, add parameters to the request |
| Animated GIF | -- |

2020-09-08 16:38 UTC, gcandal requested changes

2020-09-08 16:38 UTC, gcandal commented on js/client.js
> +         * its results
End with a period (`.`).

2020-09-08 16:38 UTC, gcandal commented on js/client.js
> +        async listClients(options) {
Default to empty options (`{}`)

2020-09-09 07:40 UTC, gcandal approved these changes

2020-09-09 08:37 UTC, joamag approved these changes

2020-09-09 08:58 UTC, joamag approved these changes

2020-09-09 08:58 UTC, merged